var data = {  
   "status":0,
   "message":"OK",
   "result":[  
      {  
         "pid":"5352366beda0c71f574f0ad2",
         "name":"fdsd",
         "description":"fdsfsfdsf",
         "storeName":"new Store Created",
         "price":23423.0,
         "groupId":"5352366aeda0c71f574f0acc",
         "autoConfirm":false,
         "mrp":423.0,
         "stockRequired":true,
         "productSkuCode":"sfds",
         "metaTitle":"",
         "metaKeywords":"",
         "keyprops":[  
            {  
               "key":"fsdf",
               "value":"fsdf",
               "type":null,
               "description":null,
               "label":null,
               "option":null
            }
         ],
         "category":[  
            {  
               "id":"52946cfc6c723c9e8ef593f7",
               "name":"Mail-Jole Ka Maza",
               "description":"sdsdsjdhskjdkjsdhskd\t\t\t\t\t\t\t",
               "maxPrice":0.0,
               "minPrice":0.0,
               "idPaths":[  
                  {  
                     "id":"52946cfc6c723c9e8ef593f7",
                     "name":"asd",
                     "maxPrice":0.0,
                     "minPrice":0.0,
                     "productCount":0,
                     "serviceCount":0,
                     "type":"product",
                     "isSystem":false
                  }
               ],
               "productCount":0,
               "serviceCount":0,
               "type":"product",
               "isSystem":false
            }
         ],
         "userReviews":{  
            "likedByUsers":null,
            "likeCounts":0,
            "commentCount":0,
            "ratingCount":0,
            "ratingByUser":null,
            "rating":0.0,
            "owners":null,
            "ownerCount":0,
            "primaryOwner":null,
            "primaryOwnerName":null,
            "secondaryOwner":null,
            "secondaryOwnerName":null,
            "publicProperty":false,
            "groupId":null,
            "lastMsg":null,
            "answered":0,
            "updatedOn":null,
            "area":null,
            "metaInfo":null
         },
         "storeId":"MALL32f",
         "likeCounts":0,
         "ratingSum":0.0,
         "commentCount":0,
         "outofstock":false,
         "cityCount":0,
         "sellableOpt":"sell",
         "newPreset":false,
         "saveAll":false
      },
      {  
         "pid":"5352361aeda0c71f574f0acb",
         "name":"fdsfsdf",
         "description":"dfsdfsdfds",
         "storeName":"new Store Created",
         "price":43232.0,
         "groupId":"5352361aeda0c71f574f0ac5",
         "autoConfirm":false,
         "mrp":423.0,
         "stockRequired":true,
         "productSkuCode":"dsfdsfs",
         "metaTitle":"",
         "metaKeywords":"",
         "keyprops":[  
            {  
               "key":"dsafd",
               "value":"fdfds",
               "type":null,
               "description":null,
               "label":null,
               "option":null
            }
         ],
         "category":[  
            {  
               "id":"52946cfc6c723c9e8ef593f7",
               "name":"Mail-Jole Ka Maza",
               "description":"sdsdsjdhskjdkjsdhskd\t\t\t\t\t\t\t",
               "maxPrice":0.0,
               "minPrice":0.0,
               "idPaths":[  
                  {  
                     "id":"52946cfc6c723c9e8ef593f7",
                     "name":"asd",
                     "maxPrice":0.0,
                     "minPrice":0.0,
                     "productCount":0,
                     "serviceCount":0,
                     "type":"product",
                     "isSystem":false
                  }
               ],
               "productCount":0,
               "serviceCount":0,
               "type":"product",
               "isSystem":false
            }
         ],
         "userReviews":{  
            "likedByUsers":null,
            "likeCounts":0,
            "commentCount":0,
            "ratingCount":0,
            "ratingByUser":null,
            "rating":0.0,
            "owners":null,
            "ownerCount":0,
            "primaryOwner":null,
            "primaryOwnerName":null,
            "secondaryOwner":null,
            "secondaryOwnerName":null,
            "publicProperty":false,
            "groupId":null,
            "lastMsg":null,
            "answered":0,
            "updatedOn":null,
            "area":null,
            "metaInfo":null
         },
         "storeId":"MALL32f",
         "likeCounts":0,
         "ratingSum":0.0,
         "commentCount":0,
         "outofstock":false,
         "cityCount":0,
         "sellableOpt":"sell",
         "newPreset":false,
         "saveAll":false
      },
      {  
         "pid":"535235f0eda0c71f574f0ac4",
         "name":"dasdsa",
         "description":"dasdasdasd",
         "storeName":"new Store Created",
         "price":23423.0,
         "groupId":"535235f0eda0c71f574f0abe",
         "autoConfirm":false,
         "mrp":4324.0,
         "stockRequired":true,
         "productSkuCode":"dsada",
         "metaTitle":"",
         "metaKeywords":"",
         "keyprops":[  
            {  
               "key":"dsadas",
               "value":"dasd",
               "type":null,
               "description":null,
               "label":null,
               "option":null
            }
         ],
         "category":[  
            {  
               "id":"52946cfc6c723c9e8ef593f7",
               "name":"Mail-Jole Ka Maza",
               "description":"sdsdsjdhskjdkjsdhskd\t\t\t\t\t\t\t",
               "maxPrice":0.0,
               "minPrice":0.0,
               "idPaths":[  
                  {  
                     "id":"52946cfc6c723c9e8ef593f7",
                     "name":"asd",
                     "maxPrice":0.0,
                     "minPrice":0.0,
                     "productCount":0,
                     "serviceCount":0,
                     "type":"product",
                     "isSystem":false
                  }
               ],
               "productCount":0,
               "serviceCount":0,
               "type":"product",
               "isSystem":false
            }
         ],
         "userReviews":{  
            "likedByUsers":null,
            "likeCounts":0,
            "commentCount":0,
            "ratingCount":0,
            "ratingByUser":null,
            "rating":0.0,
            "owners":null,
            "ownerCount":0,
            "primaryOwner":null,
            "primaryOwnerName":null,
            "secondaryOwner":null,
            "secondaryOwnerName":null,
            "publicProperty":false,
            "groupId":null,
            "lastMsg":null,
            "answered":0,
            "updatedOn":null,
            "area":null,
            "metaInfo":null
         },
         "storeId":"MALL32f",
         "likeCounts":0,
         "ratingSum":0.0,
         "commentCount":0,
         "outofstock":false,
         "cityCount":0,
         "sellableOpt":"sell",
         "newPreset":false,
         "saveAll":false
      },
      {  
         "pid":"53427f42eda0110b1040fa31",
         "name":"tyryrty",
         "description":"dsfsddfsdfs",
         "storeName":"new Store Created",
         "price":3432.0,
         "groupId":"53427f42eda0110b1040fa2f",
         "autoConfirm":false,
         "mrp":4325.0,
         "stockRequired":true,
         "productSkuCode":"dasasd",
         "metaTitle":"",
         "metaKeywords":"",
         "keyprops":[  
            {  
               "key":"",
               "value":"adfadsd",
               "type":null,
               "description":null,
               "label":null,
               "option":null
            }
         ],
         "category":[  
            {  
               "id":"52946cfc6c723c9e8ef593f7",
               "name":"Mail-Jole Ka Maza",
               "description":"sdsdsjdhskjdkjsdhskd\t\t\t\t\t\t\t",
               "maxPrice":0.0,
               "minPrice":0.0,
               "idPaths":[  
                  {  
                     "id":"52946cfc6c723c9e8ef593f7",
                     "name":"asd",
                     "maxPrice":0.0,
                     "minPrice":0.0,
                     "productCount":0,
                     "serviceCount":0,
                     "type":"product",
                     "isSystem":false
                  }
               ],
               "productCount":0,
               "serviceCount":0,
               "type":"product",
               "isSystem":false
            },
            {  
               "id":"529d8adb36a2f4de6c1ceef0",
               "name":"Chinese",
               "description":"",
               "maxPrice":0.0,
               "minPrice":0.0,
               "idPaths":[  
                  {  
                     "id":"529d8adb36a2f4de6c1ceef0",
                     "name":"adasdasdasdasd",
                     "maxPrice":0.0,
                     "minPrice":0.0,
                     "productCount":0,
                     "serviceCount":0,
                     "type":"product",
                     "isSystem":false
                  }
               ],
               "productCount":0,
               "serviceCount":0,
               "type":"product",
               "isSystem":false
            },
            {  
               "id":"529ed65536a24bbf78586474",
               "name":"Raita & Salad",
               "description":"ddsada",
               "maxPrice":0.0,
               "minPrice":0.0,
               "idPaths":[  
                  {  
                     "id":"529ed65536a24bbf78586474",
                     "name":"dasdas",
                     "maxPrice":0.0,
                     "minPrice":0.0,
                     "productCount":0,
                     "serviceCount":0,
                     "type":"product",
                     "isSystem":false
                  }
               ],
               "productCount":0,
               "serviceCount":0,
               "type":"product",
               "isSystem":false
            },
            {  
               "id":"529edfa236a24bbf7858647f",
               "name":"Papad",
               "description":"dsadas",
               "maxPrice":0.0,
               "minPrice":0.0,
               "idPaths":[  
                  {  
                     "id":"529edfa236a24bbf7858647f",
                     "name":"dasdas",
                     "maxPrice":0.0,
                     "minPrice":0.0,
                     "productCount":0,
                     "serviceCount":0,
                     "type":"product",
                     "isSystem":false
                  }
               ],
               "productCount":0,
               "serviceCount":0,
               "type":"product",
               "isSystem":false
            }
         ],
         "userReviews":{  
            "likedByUsers":null,
            "likeCounts":0,
            "commentCount":0,
            "ratingCount":0,
            "ratingByUser":null,
            "rating":0.0,
            "owners":null,
            "ownerCount":0,
            "primaryOwner":null,
            "primaryOwnerName":null,
            "secondaryOwner":null,
            "secondaryOwnerName":null,
            "publicProperty":false,
            "groupId":null,
            "lastMsg":null,
            "answered":0,
            "updatedOn":null,
            "area":null,
            "metaInfo":null
         },
         "storeId":"MALL32f",
         "likeCounts":0,
         "ratingSum":0.0,
         "commentCount":0,
         "outofstock":false,
         "cityCount":0,
         "sellableOpt":"sell",
         "newPreset":false,
         "saveAll":false
      },
      {  
         "pid":"53427eb0eda0110b1040fa2e",
         "name":"dsadasdsadsa",
         "description":"dasdasd",
         "storeName":"new Store Created",
         "price":23242.0,
         "groupId":"53427eb0eda0110b1040fa2c",
         "autoConfirm":false,
         "mrp":344324.0,
         "stockRequired":true,
         "productSkuCode":"dsadas",
         "metaTitle":"",
         "metaKeywords":"",
         "keyprops":[  
            {  
               "key":"dasd",
               "value":"sadasdasda",
               "type":null,
               "description":null,
               "label":null,
               "option":null
            }
         ],
         "category":[  
            {  
               "id":"52946cfc6c723c9e8ef593f7",
               "name":"Mail-Jole Ka Maza",
               "description":"sdsdsjdhskjdkjsdhskd\t\t\t\t\t\t\t",
               "maxPrice":0.0,
               "minPrice":0.0,
               "idPaths":[  
                  {  
                     "id":"52946cfc6c723c9e8ef593f7",
                     "name":"asd",
                     "maxPrice":0.0,
                     "minPrice":0.0,
                     "productCount":0,
                     "serviceCount":0,
                     "type":"product",
                     "isSystem":false
                  }
               ],
               "productCount":0,
               "serviceCount":0,
               "type":"product",
               "isSystem":false
            },
            {  
               "id":"529d8adb36a2f4de6c1ceef0",
               "name":"Chinese",
               "description":"",
               "maxPrice":0.0,
               "minPrice":0.0,
               "idPaths":[  
                  {  
                     "id":"529d8adb36a2f4de6c1ceef0",
                     "name":"adasdasdasdasd",
                     "maxPrice":0.0,
                     "minPrice":0.0,
                     "productCount":0,
                     "serviceCount":0,
                     "type":"product",
                     "isSystem":false
                  }
               ],
               "productCount":0,
               "serviceCount":0,
               "type":"product",
               "isSystem":false
            },
            {  
               "id":"529ed65536a24bbf78586474",
               "name":"Raita & Salad",
               "description":"ddsada",
               "maxPrice":0.0,
               "minPrice":0.0,
               "idPaths":[  
                  {  
                     "id":"529ed65536a24bbf78586474",
                     "name":"dasdas",
                     "maxPrice":0.0,
                     "minPrice":0.0,
                     "productCount":0,
                     "serviceCount":0,
                     "type":"product",
                     "isSystem":false
                  }
               ],
               "productCount":0,
               "serviceCount":0,
               "type":"product",
               "isSystem":false
            },
            {  
               "id":"529edfa236a24bbf7858647f",
               "name":"Papad",
               "description":"dsadas",
               "maxPrice":0.0,
               "minPrice":0.0,
               "idPaths":[  
                  {  
                     "id":"529edfa236a24bbf7858647f",
                     "name":"dasdas",
                     "maxPrice":0.0,
                     "minPrice":0.0,
                     "productCount":0,
                     "serviceCount":0,
                     "type":"product",
                     "isSystem":false
                  }
               ],
               "productCount":0,
               "serviceCount":0,
               "type":"product",
               "isSystem":false
            }
         ],
         "userReviews":{  
            "likedByUsers":null,
            "likeCounts":0,
            "commentCount":0,
            "ratingCount":0,
            "ratingByUser":null,
            "rating":0.0,
            "owners":null,
            "ownerCount":0,
            "primaryOwner":null,
            "primaryOwnerName":null,
            "secondaryOwner":null,
            "secondaryOwnerName":null,
            "publicProperty":false,
            "groupId":null,
            "lastMsg":null,
            "answered":0,
            "updatedOn":null,
            "area":null,
            "metaInfo":null
         },
         "storeId":"MALL32f",
         "likeCounts":0,
         "ratingSum":0.0,
         "commentCount":0,
         "outofstock":false,
         "cityCount":0,
         "sellableOpt":"sell",
         "newPreset":false,
         "saveAll":false
      },
      {  
         "pid":"540ad635eda0e2f59eea5c7b",
         "name":"sdasd",
         "description":"dsadsadasdasdasd",
         "storeName":"CREATE STORE REGISTRATION CREATE STORE REGISTRATIO",
         "storeAddress":"[sector, 18, noida, uttar, pradesh, india, 122001]",
         "price":32.0,
         "groupId":"540ad635eda0e2f59eea5c7a",
         "autoConfirm":false,
         "mrp":32.0,
         "productImage":"http://localhost:8080/svc/user/download-file/?id=user-doc\\MALL32f\\allimg\\5419303ceda096b8372ab8e9.jpeg",
         "stockRequired":true,
         "productSkuCode":"assad",
         "metaTitle":"",
         "metaKeywords":"",
         "keyprops":[  
            {  
               "key":"das",
               "value":"dad32",
               "type":null,
               "description":null,
               "label":null,
               "option":null
            }
         ],
         "category":[  
            {  
               "id":"529ef8a336a2c3fa6eb1687c",
               "name":"South-Indian",
               "description":"dasdadasd",
               "maxPrice":100000.0,
               "minPrice":10.0,
               "idPaths":[  
                  {  
                     "id":"529ef8a336a2c3fa6eb1687c",
                     "name":"South-Indian",
                     "maxPrice":100000.0,
                     "minPrice":10.0,
                     "productCount":0,
                     "serviceCount":0,
                     "type":"product",
                     "isSystem":false
                  }
               ],
               "productCount":0,
               "serviceCount":0,
               "type":"product",
               "isSystem":false
            }
         ],
         "userReviews":{  
            "likedByUsers":null,
            "likeCounts":0,
            "commentCount":0,
            "ratingCount":0,
            "ratingByUser":null,
            "rating":0.0,
            "owners":null,
            "ownerCount":0,
            "primaryOwner":null,
            "primaryOwnerName":null,
            "secondaryOwner":null,
            "secondaryOwnerName":null,
            "publicProperty":false,
            "groupId":null,
            "lastMsg":null,
            "answered":0,
            "updatedOn":null,
            "area":null,
            "metaInfo":null
         },
         "storeId":"MALL32f",
         "likeCounts":0,
         "ratingSum":0.0,
         "commentCount":0,
         "outofstock":false,
         "city":" Noida",
         "cities":[  
            {  
               "id":null,
               "locality":null,
               "city":"New Delhi",
               "state":null,
               "pincode":null,
               "country":null,
               "circleId":null,
               "lat":null,
               "lon":null,
               "loc":null,
               "taluka":null,
               "ancestor":null
            }
         ],
         "cityCount":1,
         "sellableOpt":"sell",
         "newPreset":false,
         "saveAll":false
      },
      {  
         "pid":"5371e579eda0ba7fcede978f",
         "name":"Event rock stars",
         "description":"xzxZZxZxZ",
         "storeName":"new Store Created",
         "price":32.0,
         "groupId":"5371e539eda0ba7fcede978d",
         "autoConfirm":false,
         "mrp":323.0,
         "productImage":"http://localhost:8080/svc/user/download-file/?id=/store/\\MALL32f\\productimg\\5499324deda0d75062778a16.png",
         "stockRequired":true,
         "productSkuCode":"sasa",
         "metaTitle":"",
         "metaKeywords":"",
         "keyprops":[  
            {  
               "key":"xZXZX",
               "value":"xZxz",
               "type":null,
               "description":null,
               "label":null,
               "option":null
            }
         ],
         "category":[  
            {  
               "id":"529d8adb36a2f4de6c1ceef0",
               "name":"Chinese",
               "description":"",
               "maxPrice":100000.0,
               "minPrice":10.0,
               "idPaths":[  
                  {  
                     "id":"529d8adb36a2f4de6c1ceef0",
                     "name":"Chinese",
                     "maxPrice":100000.0,
                     "minPrice":10.0,
                     "productCount":0,
                     "serviceCount":0,
                     "type":"product",
                     "isSystem":false
                  }
               ],
               "productCount":0,
               "serviceCount":0,
               "type":"product",
               "isSystem":false
            },
            {  
               "id":"529ed65d36a24bbf78586475",
               "name":"Appetizers",
               "description":"dsadsd",
               "maxPrice":100000.0,
               "minPrice":10.0,
               "idPaths":[  
                  {  
                     "id":"529ed65d36a24bbf78586475",
                     "name":"Appetizers",
                     "maxPrice":100000.0,
                     "minPrice":10.0,
                     "productCount":0,
                     "serviceCount":0,
                     "type":"product",
                     "isSystem":false
                  }
               ],
               "productCount":0,
               "serviceCount":0,
               "type":"product",
               "isSystem":false
            },
            {  
               "id":"529eddfe36a24bbf7858647e",
               "name":"Basmati-Khazana",
               "description":"",
               "maxPrice":100000.0,
               "minPrice":10.0,
               "idPaths":[  
                  {  
                     "id":"529eddfe36a24bbf7858647e",
                     "name":"Basmati-Khazana",
                     "maxPrice":100000.0,
                     "minPrice":10.0,
                     "productCount":0,
                     "serviceCount":0,
                     "type":"product",
                     "isSystem":false
                  }
               ],
               "productCount":0,
               "serviceCount":0,
               "type":"product",
               "isSystem":false
            }
         ],
         "userReviews":{  
            "likedByUsers":null,
            "likeCounts":0,
            "commentCount":0,
            "ratingCount":0,
            "ratingByUser":null,
            "rating":0.0,
            "owners":null,
            "ownerCount":0,
            "primaryOwner":null,
            "primaryOwnerName":null,
            "secondaryOwner":null,
            "secondaryOwnerName":null,
            "publicProperty":false,
            "groupId":null,
            "lastMsg":null,
            "answered":0,
            "updatedOn":null,
            "area":null,
            "metaInfo":null
         },
         "storeId":"MALL32f",
         "likeCounts":0,
         "ratingSum":0.0,
         "commentCount":0,
         "outofstock":false,
         "cities":[  
            {  
               "id":null,
               "locality":null,
               "city":" Noida",
               "state":null,
               "pincode":null,
               "country":null,
               "circleId":null,
               "lat":null,
               "lon":null,
               "loc":null,
               "taluka":null,
               "ancestor":null
            }
         ],
         "cityCount":0,
         "sellableOpt":"sell",
         "newPreset":false,
         "saveAll":false
      },
      {  
         "pid":"52d52be558f6fa6db3e34abc",
         "name":"fdsfdsfdsfdsf",
         "description":"fdsfdsfdsfdsfsdfsdf",
         "storeName":"ansbaj",
         "storeAddress":"[safdarjung, enclave, new, delhi, delhi, india, safdarjung, enclave, new, delhi, delhi, india,212121212]",
         "price":4.3243,
         "groupId":"52d5175358f6108e7b481939",
         "autoConfirm":false,
         "mrp":3.243,
         "productImage":"http://localhost:8080/svc/user/download-file/?id=user-doc\\MALL32f\\allimg\\53e9ba0feda0d1356bd438ee.jpeg",
         "stockRequired":true,
         "metaTitle":"gfdgdfgdfgdg",
         "metaKeywords":"gfdgdfgdfgdg",
         "keyprops":[  
            {  
               "key":"fsdfsdf",
               "value":"sdfdsfdsf",
               "type":null,
               "description":null,
               "label":null,
               "option":null
            }
         ],
         "category":[  
            {  
               "id":"52d0e2778a54d4af082aae0f",
               "name":"dsadsad",
               "description":"asdasdasdasda",
               "maxPrice":0.0,
               "minPrice":0.0,
               "idPaths":[  
                  {  
                     "id":"52d0e2778a54d4af082aae0f",
                     "name":"dsadsad",
                     "maxPrice":0.0,
                     "minPrice":0.0,
                     "productCount":0,
                     "serviceCount":0,
                     "type":"product",
                     "isSystem":false
                  }
               ],
               "productCount":0,
               "serviceCount":0,
               "type":"product",
               "isSystem":false
            }
         ],
         "userReviews":{  
            "likedByUsers":null,
            "likeCounts":80,
            "commentCount":0,
            "ratingCount":0,
            "ratingByUser":null,
            "rating":0.0,
            "owners":null,
            "ownerCount":0,
            "primaryOwner":null,
            "primaryOwnerName":null,
            "secondaryOwner":null,
            "secondaryOwnerName":null,
            "publicProperty":false,
            "groupId":null,
            "lastMsg":null,
            "answered":0,
            "updatedOn":null,
            "area":null,
            "metaInfo":null
         },
         "storeId":"MALL32f",
         "likeCounts":80,
         "ratingSum":0.0,
         "commentCount":0,
         "properties":[  
            {  
               "id":"52d5176258f6108e7b48193c",
               "storeId":"MALLfa4",
               "name":"fdsfdsf",
               "preset":[  
                  {  
                     "key":"dsfsdfds",
                     "value":"fdsfd",
                     "type":null,
                     "description":null,
                     "label":null,
                     "option":null
                  },
                  {  
                     "key":"fsdfds",
                     "value":"fdsfds",
                     "type":null,
                     "description":null,
                     "label":null,
                     "option":null
                  }
               ]
            }
         ],
         "outofstock":false,
         "cityCount":0,
         "sellableOpt":"sell",
         "newPreset":false,
         "saveAll":false
      },
      {  
         "pid":"53d9122ceda0f83c598d9c6a",
         "name":"fdsfdsfdsfdsf",
         "description":"fdsfdsfdsfdsfsdfsdf",
         "storeName":"new Store Created",
         "storeAddress":"[sector, 18, noida, uttar, pradesh, india, 122001]",
         "price":2.3243,
         "groupId":"52d5175358f6108e7b481939",
         "autoConfirm":false,
         "mrp":3.243,
         "productImage":"http://localhost:8080/svc/user/download-file/?id=user-doc\\MALL32f\\allimg\\53e9ba24eda0d1356bd438f6.jpeg",
         "stockRequired":true,
         "productSkuCode":"dsdadd",
         "metaTitle":"gfdgdfgdfgdg",
         "metaKeywords":"gfdgdfgdfgdg",
         "keyprops":[  
            {  
               "key":"fsdfsdf",
               "value":"sdfdsfdsf",
               "type":null,
               "description":null,
               "label":null,
               "option":null
            }
         ],
         "category":[  
            {  
               "id":"529d8adb36a2f4de6c1ceef0",
               "name":"Chinese",
               "description":"",
               "maxPrice":100000.0,
               "minPrice":10.0,
               "idPaths":[  
                  {  
                     "id":"529d8adb36a2f4de6c1ceef0",
                     "name":"Chinese",
                     "maxPrice":100000.0,
                     "minPrice":10.0,
                     "productCount":0,
                     "serviceCount":0,
                     "type":"product",
                     "isSystem":false
                  }
               ],
               "productCount":0,
               "serviceCount":0,
               "type":"product",
               "isSystem":false
            },
            {  
               "id":"529eda9c36a24bbf78586479",
               "name":"Sony",
               "description":"ffdsfsd",
               "maxPrice":100000.0,
               "minPrice":10.0,
               "idPaths":[  
                  {  
                     "id":"529eda9c36a24bbf78586479",
                     "name":"Sony",
                     "maxPrice":100000.0,
                     "minPrice":10.0,
                     "productCount":0,
                     "serviceCount":0,
                     "type":"product",
                     "isSystem":false
                  }
               ],
               "productCount":0,
               "serviceCount":0,
               "type":"product",
               "isSystem":false
            },
            {  
               "id":"529eddfe36a24bbf7858647e",
               "name":"Basmati-Khazana",
               "description":"",
               "maxPrice":100000.0,
               "minPrice":10.0,
               "idPaths":[  
                  {  
                     "id":"529eddfe36a24bbf7858647e",
                     "name":"Basmati-Khazana",
                     "maxPrice":100000.0,
                     "minPrice":10.0,
                     "productCount":0,
                     "serviceCount":0,
                     "type":"product",
                     "isSystem":false
                  }
               ],
               "productCount":0,
               "serviceCount":0,
               "type":"product",
               "isSystem":false
            }
         ],
         "userReviews":{  
            "likedByUsers":null,
            "likeCounts":0,
            "commentCount":0,
            "ratingCount":0,
            "ratingByUser":null,
            "rating":0.0,
            "owners":null,
            "ownerCount":0,
            "primaryOwner":null,
            "primaryOwnerName":null,
            "secondaryOwner":null,
            "secondaryOwnerName":null,
            "publicProperty":false,
            "groupId":null,
            "lastMsg":null,
            "answered":0,
            "updatedOn":null,
            "area":null,
            "metaInfo":null
         },
         "storeId":"MALL32f",
         "likeCounts":0,
         "ratingSum":0.0,
         "commentCount":0,
         "properties":[  
            {  
               "id":"52d5176258f6108e7b48193c",
               "storeId":"MALLfa4",
               "name":"fdsfdsf",
               "preset":[  
                  {  
                     "key":"dsfsdfds",
                     "value":"fdsfd",
                     "type":null,
                     "description":null,
                     "label":null,
                     "option":null
                  },
                  {  
                     "key":"fsdfds",
                     "value":"fdsfds",
                     "type":null,
                     "description":null,
                     "label":null,
                     "option":null
                  }
               ]
            }
         ],
         "outofstock":false,
         "city":" Noida",
         "cityCount":0,
         "sellableOpt":"sell",
         "newPreset":false,
         "saveAll":false
      },
      {  
         "pid":"53d912ddeda0f83c598d9c6e",
         "name":"Please don't shave",
         "description":"fdsfdsfdsfdsfsdfsdf",
         "storeName":"new Store Created",
         "storeAddress":"[sector, 18, noida, uttar, pradesh, india, 122001]",
         "price":40.0,
         "groupId":"52d5175358f6108e7b481939",
         "autoConfirm":false,
         "mrp":55.0,
         "productImage":"http://localhost:8080/svc/user/download-file/?id=/store/\\MALL32f\\productimg\\5499320feda0d750627789fb.jpeg",
         "stockRequired":true,
         "productSkuCode":"jhjkjkhkj",
         "metaTitle":"gfdgdfgdfgdg",
         "metaKeywords":"gfdgdfgdfgdg",
         "keyprops":[  
            {  
               "key":"fsdfsdf",
               "value":"sdfdsfdsf",
               "type":null,
               "description":null,
               "label":null,
               "option":null
            }
         ],
         "category":[  
            {  
               "id":"529d8ad736a2f4de6c1ceeee",
               "name":"Subz-Bagh",
               "description":"\t\t\t\t\t\t\t",
               "maxPrice":100000.0,
               "minPrice":10.0,
               "idPaths":[  
                  {  
                     "id":"529d8ad736a2f4de6c1ceeee",
                     "name":"Subz-Bagh",
                     "maxPrice":100000.0,
                     "minPrice":10.0,
                     "productCount":0,
                     "serviceCount":0,
                     "type":"product",
                     "isSystem":false
                  }
               ],
               "productCount":0,
               "serviceCount":0,
               "type":"product",
               "isSystem":false
            },
            {  
               "id":"529eda9c36a24bbf78586479",
               "name":"Sony",
               "description":"ffdsfsd",
               "maxPrice":100000.0,
               "minPrice":10.0,
               "idPaths":[  
                  {  
                     "id":"529eda9c36a24bbf78586479",
                     "name":"Sony",
                     "maxPrice":100000.0,
                     "minPrice":10.0,
                     "productCount":0,
                     "serviceCount":0,
                     "type":"product",
                     "isSystem":false
                  }
               ],
               "productCount":0,
               "serviceCount":0,
               "type":"product",
               "isSystem":false
            },
            {  
               "id":"529ef8a336a2c3fa6eb1687c",
               "name":"South-Indian",
               "description":"dasdadasd",
               "maxPrice":100000.0,
               "minPrice":10.0,
               "idPaths":[  
                  {  
                     "id":"529ef8a336a2c3fa6eb1687c",
                     "name":"South-Indian",
                     "maxPrice":100000.0,
                     "minPrice":10.0,
                     "productCount":0,
                     "serviceCount":0,
                     "type":"product",
                     "isSystem":false
                  }
               ],
               "productCount":0,
               "serviceCount":0,
               "type":"product",
               "isSystem":false
            },
            {  
               "id":"529ef92736a2c3fa6eb1687e",
               "name":"Nokia",
               "description":"fdsfsdfsd",
               "maxPrice":100000.0,
               "minPrice":10.0,
               "idPaths":[  
                  {  
                     "id":"529ef92736a2c3fa6eb1687e",
                     "name":"Nokia",
                     "maxPrice":100000.0,
                     "minPrice":10.0,
                     "productCount":0,
                     "serviceCount":0,
                     "type":"product",
                     "isSystem":false
                  }
               ],
               "productCount":0,
               "serviceCount":0,
               "type":"product",
               "isSystem":false
            }
         ],
         "userReviews":{  
            "likedByUsers":null,
            "likeCounts":0,
            "commentCount":0,
            "ratingCount":0,
            "ratingByUser":null,
            "rating":0.0,
            "owners":null,
            "ownerCount":0,
            "primaryOwner":null,
            "primaryOwnerName":null,
            "secondaryOwner":null,
            "secondaryOwnerName":null,
            "publicProperty":false,
            "groupId":null,
            "lastMsg":null,
            "answered":0,
            "updatedOn":null,
            "area":null,
            "metaInfo":null
         },
         "storeId":"MALL32f",
         "likeCounts":0,
         "ratingSum":0.0,
         "commentCount":0,
         "properties":[  
            {  
               "id":"52d5176258f6108e7b48193c",
               "storeId":"MALLfa4",
               "name":"fdsfdsf",
               "preset":[  
                  {  
                     "key":"dsfsdfds",
                     "value":"fdsfd",
                     "type":null,
                     "description":null,
                     "label":null,
                     "option":null
                  },
                  {  
                     "key":"fsdfds",
                     "value":"fdsfds",
                     "type":null,
                     "description":null,
                     "label":null,
                     "option":null
                  }
               ]
            }
         ],
         "outofstock":false,
         "city":" Noida",
         "cities":[  
            {  
               "id":null,
               "locality":null,
               "city":"New Delhi",
               "state":null,
               "pincode":null,
               "country":null,
               "circleId":null,
               "lat":null,
               "lon":null,
               "loc":null,
               "taluka":null,
               "ancestor":null
            }
         ],
         "cityCount":1,
         "sellableOpt":"sell",
         "newPreset":false,
         "saveAll":false
      },
      {  
         "pid":"p-548012d5eda001b8286bd78d",
         "name":"Test product",
         "description":"http://localhost:8080/admin/product/create/register?from=product",
         "storeName":"Medanta Hospital",
         "storeAddress":"[sector, 18, noida, uttar, pradesh, india, 122001]",
         "price":32.0,
         "groupId":"p-548012d5eda001b8286bd78d",
         "autoConfirm":false,
         "mrp":32.0,
         "productImage":"http://localhost:8080/svc/user/download-file/?id=/store/\\MALL32f\\productimg\\5480130ceda001b8286bd7a1.jpeg",
         "stockRequired":true,
         "productSkuCode":"asdsadssads",
         "metaTitle":"",
         "metaKeywords":"",
         "keyprops":[  
            {  
               "key":"dsadad",
               "value":"sadsadsada",
               "type":null,
               "description":null,
               "label":null,
               "option":null
            }
         ],
         "category":[  

         ],
         "userReviews":{  
            "likedByUsers":null,
            "likeCounts":0,
            "commentCount":0,
            "ratingCount":0,
            "ratingByUser":null,
            "rating":0.0,
            "owners":null,
            "ownerCount":0,
            "primaryOwner":null,
            "primaryOwnerName":null,
            "secondaryOwner":null,
            "secondaryOwnerName":null,
            "publicProperty":false,
            "groupId":null,
            "lastMsg":null,
            "answered":0,
            "updatedOn":null,
            "area":null,
            "metaInfo":null
         },
         "storeId":"MALL32f",
         "likeCounts":0,
         "ratingSum":0.0,
         "commentCount":0,
         "properties":[  
            {  
               "id":"548012fceda001b8286bd799",
               "storeId":"MALL32f",
               "presetId":"548012f5eda001b8286bd792",
               "name":"sadsadas",
               "preset":[  
                  {  
                     "key":"dasdsdsad",
                     "value":"dsadasd",
                     "type":null,
                     "description":null,
                     "label":null,
                     "option":null
                  },
                  {  
                     "key":"dasdadasd",
                     "value":"asdsadsadasd",
                     "type":null,
                     "description":null,
                     "label":null,
                     "option":null
                  }
               ]
            },
            {  
               "id":"548012fceda001b8286bd79a",
               "storeId":"MALL32f",
               "presetId":"548012f5eda001b8286bd793",
               "name":"asdasda",
               "preset":[  
                  {  
                     "key":"sdasdasd",
                     "value":"dsadsa",
                     "type":null,
                     "description":null,
                     "label":null,
                     "option":null
                  },
                  {  
                     "key":"adadasdadas",
                     "value":"dsadsa",
                     "type":null,
                     "description":null,
                     "label":null,
                     "option":null
                  }
               ]
            },
            {  
               "id":"548012fceda001b8286bd79b",
               "storeId":"MALL32f",
               "presetId":"548012f5eda001b8286bd794",
               "name":"dsadasda",
               "preset":[  
                  {  
                     "key":"dasdasd\t\t\t\t\t\t\t\t\t\t",
                     "value":"dsadsas",
                     "type":null,
                     "description":null,
                     "label":null,
                     "option":null
                  },
                  {  
                     "key":"adasdadasd\t\t\t\t\t\t\t\t\t\t,dsadasdasda",
                     "value":"sadadsads",
                     "type":null,
                     "description":null,
                     "label":null,
                     "option":null
                  }
               ]
            }
         ],
         "outofstock":false,
         "city":" Noida",
         "cityCount":0,
         "sellableOpt":"sell",
         "newPreset":false,
         "saveAll":false
      },
      {  
         "pid":"p-54801550eda001b8286bd7a9",
         "name":"Celeberations",
         "description":"sadsad",
         "storeName":"Medanta Hospital",
         "storeAddress":"[sector, 18, noida, uttar, pradesh, india, 122001]",
         "price":2.0,
         "groupId":"p-54801550eda001b8286bd7a9",
         "autoConfirm":false,
         "mrp":2.0,
         "productImage":"http://localhost:8080/svc/user/download-file/?id=/store/\\MALL32f\\productimg\\54993161eda0d750627789c4.jpeg",
         "stockRequired":true,
         "productSkuCode":"dasdasdsa",
         "metaTitle":"",
         "metaKeywords":"",
         "keyprops":[  
            {  
               "key":"dsa",
               "value":"dsa",
               "type":null,
               "description":null,
               "label":null,
               "option":null
            }
         ],
         "category":[  
            {  
               "id":"52986938680060b9ce337c63",
               "name":"ELECTRONICS",
               "description":"\t\t\t\t\t\t\tfsfdfdddd",
               "maxPrice":100000.0,
               "minPrice":10.0,
               "idPaths":[  
                  {  
                     "id":"52986938680060b9ce337c63",
                     "name":"ELECTRONICS",
                     "maxPrice":100000.0,
                     "minPrice":10.0,
                     "productCount":0,
                     "serviceCount":0,
                     "type":"product",
                     "isSystem":false
                  }
               ],
               "productCount":0,
               "serviceCount":0,
               "type":"product",
               "isSystem":false
            },
            {  
               "id":"529ed65d36a24bbf78586475",
               "name":"Appetizers",
               "description":"dsadsd",
               "maxPrice":100000.0,
               "minPrice":10.0,
               "idPaths":[  
                  {  
                     "id":"529ed65d36a24bbf78586475",
                     "name":"Appetizers",
                     "maxPrice":100000.0,
                     "minPrice":10.0,
                     "productCount":0,
                     "serviceCount":0,
                     "type":"product",
                     "isSystem":false
                  }
               ],
               "productCount":0,
               "serviceCount":0,
               "type":"product",
               "isSystem":false
            },
            {  
               "id":"52a5cf766800f17abb918c1e",
               "name":"BABY & KIDS",
               "description":"sdaddasdasdas",
               "maxPrice":100000.0,
               "minPrice":10.0,
               "idPaths":[  
                  {  
                     "id":"52a5cf766800f17abb918c1e",
                     "name":"BABY & KIDS",
                     "maxPrice":100000.0,
                     "minPrice":10.0,
                     "productCount":0,
                     "serviceCount":0,
                     "type":"product",
                     "isSystem":false
                  }
               ],
               "productCount":0,
               "serviceCount":0,
               "type":"product",
               "isSystem":false
            },
            {  
               "id":"52a5cff06800f17abb918c20",
               "name":"Footwear",
               "description":"dadsdasdasdasasdasdasd",
               "maxPrice":100000.0,
               "minPrice":10.0,
               "idPaths":[  
                  {  
                     "id":"52a5cff06800f17abb918c20",
                     "name":"Footwear",
                     "maxPrice":100000.0,
                     "minPrice":10.0,
                     "productCount":0,
                     "serviceCount":0,
                     "type":"service",
                     "isSystem":false
                  }
               ],
               "productCount":0,
               "serviceCount":0,
               "type":"product",
               "isSystem":true
            },
            {  
               "id":"530dcaebf853b07cc201ccf7",
               "name":"Girls Clothing",
               "description":"sadasdasd",
               "maxPrice":100000.0,
               "minPrice":10.0,
               "idPaths":[  
                  {  
                     "id":"530dcaebf853b07cc201ccf7",
                     "name":"Girls Clothing",
                     "maxPrice":0.0,
                     "minPrice":0.0,
                     "productCount":0,
                     "serviceCount":0,
                     "type":"product",
                     "isSystem":false
                  }
               ],
               "productCount":0,
               "serviceCount":0,
               "type":"product",
               "isSystem":false
            }
         ],
         "userReviews":{  
            "likedByUsers":null,
            "likeCounts":0,
            "commentCount":0,
            "ratingCount":0,
            "ratingByUser":null,
            "rating":0.0,
            "owners":null,
            "ownerCount":0,
            "primaryOwner":null,
            "primaryOwnerName":null,
            "secondaryOwner":null,
            "secondaryOwnerName":null,
            "publicProperty":false,
            "groupId":null,
            "lastMsg":null,
            "answered":0,
            "updatedOn":null,
            "area":null,
            "metaInfo":null
         },
         "storeId":"MALL32f",
         "likeCounts":0,
         "ratingSum":0.0,
         "commentCount":0,
         "outofstock":false,
         "city":" Noida",
         "cityCount":0,
         "sellableOpt":"sell",
         "newPreset":false,
         "saveAll":false
      },
      {  
         "pid":"p-5480290aeda001b8286bd7d1",
         "name":"asdsa",
         "description":"dsadsadsa",
         "storeName":"Medanta Hospital",
         "storeAddress":"[sector, 18, noida, uttar, pradesh, india, 122001]",
         "price":2.0,
         "groupId":"p-5480290aeda001b8286bd7d1",
         "autoConfirm":false,
         "mrp":2.0,
         "productImage":"http://localhost:8080/svc/user/download-file/?id=/store/\\MALL32f\\productimg\\54802938eda001b8286bd7d7.jpeg",
         "stockRequired":true,
         "productSkuCode":"asdsadsa",
         "metaTitle":"",
         "metaKeywords":"",
         "keyprops":[  
            {  
               "key":"dsadsa",
               "value":"dsa",
               "type":null,
               "description":null,
               "label":null,
               "option":null
            }
         ],
         "category":[  

         ],
         "userReviews":{  
            "likedByUsers":null,
            "likeCounts":0,
            "commentCount":0,
            "ratingCount":0,
            "ratingByUser":null,
            "rating":0.0,
            "owners":null,
            "ownerCount":0,
            "primaryOwner":null,
            "primaryOwnerName":null,
            "secondaryOwner":null,
            "secondaryOwnerName":null,
            "publicProperty":false,
            "groupId":null,
            "lastMsg":null,
            "answered":0,
            "updatedOn":null,
            "area":null,
            "metaInfo":null
         },
         "storeId":"MALL32f",
         "likeCounts":0,
         "ratingSum":0.0,
         "commentCount":0,
         "properties":[  
            {  
               "id":"54802956eda001b8286bd7e6",
               "storeId":"MALL32f",
               "name":"sadsdsad",
               "preset":[  
                  {  
                     "key":"dsadsad",
                     "value":"dsadsa",
                     "type":null,
                     "description":null,
                     "label":null,
                     "option":null
                  },
                  {  
                     "key":"sadad",
                     "value":"sadasdas",
                     "type":null,
                     "description":null,
                     "label":null,
                     "option":null
                  }
               ]
            }
         ],
         "outofstock":false,
         "city":" Noida",
         "cityCount":0,
         "sellableOpt":"sell",
         "newPreset":false,
         "saveAll":false
      },
      {  
         "pid":"p-54956d01eda0b411efc29944",
         "name":"Sub Variant",
         "description":"sadsadsasadasdsad",
         "storeName":"Medanta Hospital",
         "storeAddress":"[sector, 18, noida, uttar, pradesh, india, 122001]",
         "price":23.0,
         "groupId":"53427380eda0110b1040fa0f",
         "autoConfirm":false,
         "mrp":32.0,
         "productImage":"http://localhost:8080/svc/user/download-file/?id=/store/\\MALL32f\\productimg\\54956d0eeda0b411efc2994d.jpeg",
         "stockRequired":true,
         "productSkuCode":"asdsadsadasd",
         "metaTitle":"",
         "metaKeywords":"",
         "keyprops":[  
            {  
               "key":"dsadsa",
               "value":"dsadsadsad",
               "type":null,
               "description":null,
               "label":null,
               "option":null
            },
            {  
               "key":"dsadsa",
               "value":"dsadsa",
               "type":null,
               "description":null,
               "label":null,
               "option":null
            }
         ],
         "category":[  
            {  
               "id":"52986938680060b9ce337c63",
               "name":"ELECTRONICS",
               "description":"\t\t\t\t\t\t\tfsfdfdddd",
               "maxPrice":100000.0,
               "minPrice":10.0,
               "idPaths":[  
                  {  
                     "id":"52986938680060b9ce337c63",
                     "name":"ELECTRONICS",
                     "maxPrice":100000.0,
                     "minPrice":10.0,
                     "productCount":0,
                     "serviceCount":0,
                     "type":"product",
                     "isSystem":false
                  }
               ],
               "productCount":0,
               "serviceCount":0,
               "type":"product",
               "isSystem":false
            },
            {  
               "id":"529ed65d36a24bbf78586475",
               "name":"Appetizers",
               "description":"dsadsd",
               "maxPrice":100000.0,
               "minPrice":10.0,
               "idPaths":[  
                  {  
                     "id":"529ed65d36a24bbf78586475",
                     "name":"Appetizers",
                     "maxPrice":100000.0,
                     "minPrice":10.0,
                     "productCount":0,
                     "serviceCount":0,
                     "type":"product",
                     "isSystem":false
                  }
               ],
               "productCount":0,
               "serviceCount":0,
               "type":"product",
               "isSystem":false
            },
            {  
               "id":"52a5cf766800f17abb918c1e",
               "name":"BABY & KIDS",
               "description":"sdaddasdasdas",
               "maxPrice":100000.0,
               "minPrice":10.0,
               "idPaths":[  
                  {  
                     "id":"52a5cf766800f17abb918c1e",
                     "name":"BABY & KIDS",
                     "maxPrice":100000.0,
                     "minPrice":10.0,
                     "productCount":0,
                     "serviceCount":0,
                     "type":"product",
                     "isSystem":false
                  }
               ],
               "productCount":0,
               "serviceCount":0,
               "type":"product",
               "isSystem":false
            },
            {  
               "id":"530dcaebf853b07cc201ccf7",
               "name":"Girls Clothing",
               "description":"sadasdasd",
               "maxPrice":100000.0,
               "minPrice":10.0,
               "idPaths":[  
                  {  
                     "id":"530dcaebf853b07cc201ccf7",
                     "name":"Girls Clothing",
                     "maxPrice":0.0,
                     "minPrice":0.0,
                     "productCount":0,
                     "serviceCount":0,
                     "type":"product",
                     "isSystem":false
                  }
               ],
               "productCount":0,
               "serviceCount":0,
               "type":"product",
               "isSystem":true
            }
         ],
         "userReviews":{  
            "likedByUsers":null,
            "likeCounts":0,
            "commentCount":0,
            "ratingCount":0,
            "ratingByUser":null,
            "rating":0.0,
            "owners":null,
            "ownerCount":0,
            "primaryOwner":null,
            "primaryOwnerName":null,
            "secondaryOwner":null,
            "secondaryOwnerName":null,
            "publicProperty":false,
            "groupId":null,
            "lastMsg":null,
            "answered":0,
            "updatedOn":null,
            "area":null,
            "metaInfo":null
         },
         "storeId":"MALL32f",
         "likeCounts":0,
         "ratingSum":0.0,
         "commentCount":0,
         "outofstock":false,
         "city":" Noida",
         "cityCount":0,
         "sellableOpt":"sell",
         "newPreset":false,
         "saveAll":false
      },
      {  
         "pid":"540ad658eda0e2f59eea5c7d",
         "name":"house hold paintings",
         "description":"dsadasdasdad",
         "storeName":"CREATE STORE REGISTRATION CREATE STORE REGISTRATIO",
         "storeAddress":"[sector, 18, noida, uttar, pradesh, india, 122001]",
         "price":4.0,
         "groupId":"540ad658eda0e2f59eea5c7c",
         "autoConfirm":false,
         "mrp":4.0,
         "productImage":"http://localhost:8080/svc/user/download-file/?id=/store/\\MALL32f\\productimg\\54993074eda0d75062778910.jpeg",
         "stockRequired":true,
         "productSkuCode":"adsadsad",
         "metaTitle":"",
         "metaKeywords":"",
         "keyprops":[  
            {  
               "key":"asdsad",
               "value":"ada",
               "type":null,
               "description":null,
               "label":null,
               "option":null
            }
         ],
         "category":[  
            {  
               "id":"529ef8a336a2c3fa6eb1687c",
               "name":"South-Indian",
               "description":"dasdadasd",
               "maxPrice":100000.0,
               "minPrice":10.0,
               "idPaths":[  
                  {  
                     "id":"529ef8a336a2c3fa6eb1687c",
                     "name":"South-Indian",
                     "maxPrice":100000.0,
                     "minPrice":10.0,
                     "productCount":0,
                     "serviceCount":0,
                     "type":"product",
                     "isSystem":false
                  }
               ],
               "productCount":0,
               "serviceCount":0,
               "type":"product",
               "isSystem":false
            }
         ],
         "userReviews":{  
            "likedByUsers":null,
            "likeCounts":0,
            "commentCount":0,
            "ratingCount":0,
            "ratingByUser":null,
            "rating":0.0,
            "owners":null,
            "ownerCount":0,
            "primaryOwner":null,
            "primaryOwnerName":null,
            "secondaryOwner":null,
            "secondaryOwnerName":null,
            "publicProperty":false,
            "groupId":null,
            "lastMsg":null,
            "answered":0,
            "updatedOn":null,
            "area":null,
            "metaInfo":null
         },
         "storeId":"MALL32f",
         "likeCounts":0,
         "ratingSum":0.0,
         "commentCount":0,
         "outofstock":false,
         "city":" Noida",
         "cityCount":0,
         "sellableOpt":"sell",
         "newPreset":false,
         "saveAll":false
      }
   ],
   "page":{  
      "pageSize":15,
      "start":15,
      "total":0,
      "hasMore":true
   },
   "rId":null,
   "saveUrl":null,
   "saveRequest":null,
   "extra":null
};